version: 2
jobs:
    build:
          machine:
                - image: ubuntu-2404:current
          working_directory: ~/Deploy-06182024
          steps:
          #1 Obtain repo from Github
          - checkout
          #2 Create a virtual environment and install dependencies
          -run:
                name: install dependencies
                command: |
					python3 -m venv venv
					. venv/bin/activate
					pip install -r requirements.txt
            #3 Run coding convention software plus teste
            -run:
                name: run tests
                command: |
                        . venv/bin/activate
                        flake8 –-exclude=venv* --statistics
                        # pytest -v --cov=calculator
                        pytest –-junitxml=test-results/junit.xml
            - store_test_results:
                    path: test-results
            - store_artifacts:
            path: test-results
