# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

# For a detailed guide to building and testing with Python, read the docs:
# https://circleci.com/docs/language-python/ for more details
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
#Python CircleCI 2.0 configuration file
version: 2
jobs:
build:
docker:
- image: circleci/python:3.7
working_directory: ~/devops
steps:
#1 Obtain repo from Github
- checkout
#2 Create a virtual environment and install dependencies
-run:
name: install dependencies
command: |
python3 -m venv venv
. venv/bin/activate
pip install -r requirements.txt
#3 Run coding convention software plus tester.
-run:
name: run tests
command: |
. venv/bin/activate
flake8 –-exclude=venv* --statistics
# pytest -v --cov=calculator
pytest –-junitxml=test-results/junit.xml
- store_test_results:
path: test-results
- store_artifacts:
path: test-result